/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
    war
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // implementation: 라이브러리가 빌드 시점과 런타임에 모두 필요함.
    // compileOnly: 라이브러리가 컴파일 시점에만 필요하고, 런타임에는 필요하지 않음.
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")
    // https://mvnrepository.com/artifact/org.mockito/mockito-core
    testImplementation("org.mockito:mockito-core:5.7.0")

    implementation("com.google.guava:guava:30.1.1-jre")

    // https://mvnrepository.com/artifact/jakarta.servlet/jakarta.servlet-api
    compileOnly("jakarta.servlet:jakarta.servlet-api:6.1.0-M1")
}

application {
    // Define the main class for the application.
    mainClass.set("Java.App")
}
