/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.4/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
    war
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.3")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:32.1.1-jre")

    // Spring Web MVC
    implementation("org.springframework:spring-webmvc:6.1.1")

    // Servlet(jakarta로 통일해야함)
    compileOnly("jakarta.servlet:jakarta.servlet-api:6.0.0")

    // JSP
    compileOnly("jakarta.servlet.jsp:jakarta.servlet.jsp-api:3.1.1") // api
    implementation("org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.1") // 구현체

    // JSTL
    implementation("jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:2.0.0")
    
    // Tomcat for running servlets and JSP
    implementation("org.apache.tomcat.embed:tomcat-embed-jasper:10.1.16")

    // Json
    implementation("com.fasterxml.jackson.core:jackson-core:2.16.0")

    // Mybatis
    implementation("org.mybatis:mybatis:3.5.14")
    implementation("org.mybatis:mybatis-spring:3.0.3")
    implementation("org.springframework:spring-jdbc:6.1.1")
    implementation("commons-dbcp:commons-dbcp:1.4")

    // PostgreSQL
    implementation("org.postgresql:postgresql:42.7.0")
}

// Java 컴파일러의 인코딩을 UTF-8로 설정
tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("java_spring.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
